stages:
  - setup
  - checks

install_dependencies:
  stage: setup
  image: node:20
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull-push
  script:
    - yarn install --frozen-lockfile
  only:
    - merge_requests

linter:
  stage: checks
  image: node:20
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
  script:
    - yarn check:lint
  needs:
    - install_dependencies
  only:
    - merge_requests

prettier:
  stage: checks
  image: node:20
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
  script:
    - yarn check:prettier
  needs:
    - install_dependencies
  only:
    - merge_requests

type-checking:
  stage: checks
  image: node:20
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
  script:
    - yarn check:types
  needs:
    - install_dependencies
  only:
    - merge_requests
