variables:
  NODE_IMAGE: node:20

cache:
  key:
    files:
      - yarn.lock
      - prisma/schema.prisma
  paths:
    - node_modules/
  policy: pull-push

stages:
  - setup
  - checks
  - deploy

install_dependencies:
  stage: setup
  image: $NODE_IMAGE
  script: yarn install --frozen-lockfile
  only:
    - merge_requests
    - develop
    - master

linter:
  stage: checks
  image: $NODE_IMAGE
  script: yarn check:lint
  needs:
    - install_dependencies
  only:
    - merge_requests
    - develop
    - master

prettier:
  stage: checks
  image: $NODE_IMAGE
  script: yarn check:prettier
  needs:
    - install_dependencies
  only:
    - merge_requests
    - develop
    - master

type_checking:
  stage: checks
  image: $NODE_IMAGE
  script: yarn check:types
  needs:
    - install_dependencies
  only:
    - merge_requests
    - develop
    - master

deploy:
  stage: deploy
  script:
    - docker compose -f docker-compose.yml up -d --build
  needs:
    - linter
    - prettier
    - type_checking
  tags:
    - gallery
    - backend
    - production
  only:
    - master
