variables:
  NODE_IMAGE: node:20

stages:
  - setup
  - checks
  - deploy

install_dependencies:
  stage: setup
  image: $NODE_IMAGE
  script:
    - yarn install --frozen-lockfile
    - yarn prisma generate
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull-push
  only:
    - merge_requests
    - develop
    - master

linter:
  stage: checks
  image: $NODE_IMAGE
  script:
    - yarn check:lint
  needs:
    - install_dependencies
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  only:
    - merge_requests
    - develop
    - master

prettier:
  stage: checks
  image: $NODE_IMAGE
  script:
    - yarn check:prettier
  needs:
    - install_dependencies
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  only:
    - merge_requests
    - develop
    - master

type_checking:
  stage: checks
  image: $NODE_IMAGE
  script:
    - yarn check:types
  needs:
    - install_dependencies
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  only:
    - merge_requests
    - develop
    - master

deploy:
  stage: deploy
  script:
    - docker compose -f docker-compose.yml up -d --build
  needs:
    - linter
    - prettier
    - type_checking
  tags:
    - gallery
    - backend
    - production
  only:
    - master
