variables:
  NODE_IMAGE: node:20

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/
  policy: pull-push

stages:
  - setup
  - checks

install_dependencies:
  stage: setup
  image: $NODE_IMAGE
  script: yarn install --frozen-lockfile
  only:
    - merge_requests

linter:
  stage: checks
  image: $NODE_IMAGE
  script: yarn check:lint
  needs:
    - install_dependencies
  only:
    - merge_requests

prettier:
  stage: checks
  image: $NODE_IMAGE
  script: yarn check:prettier
  needs:
    - install_dependencies
  only:
    - merge_requests

type_checking:
  stage: checks
  image: $NODE_IMAGE
  script: yarn check:types
  needs:
    - install_dependencies
  only:
    - merge_requests
