variables:
  NODE_IMAGE: node:24-slim

stages:
  - setup
  - checks
  - deploy

install_dependencies:
  stage: setup
  image: $NODE_IMAGE
  script:
    - yarn install --frozen-lockfile
    - yarn prisma generate
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull-push
  rules:
    # Запускается для merge request в develop/master
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master")
    # Запускается при пуше в master
    - if: $CI_COMMIT_BRANCH == "master"

linter:
  stage: checks
  image: $NODE_IMAGE
  script:
    - yarn check:lint
  needs:
    - install_dependencies
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  rules:
    # Запускается для merge request в develop/master
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master")
    # Запускается при пуше в master
    - if: $CI_COMMIT_BRANCH == "master"

prettier:
  stage: checks
  image: $NODE_IMAGE
  script:
    - yarn check:prettier
  needs:
    - install_dependencies
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  rules:
    # Запускается для merge request в develop/master
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master")
    # Запускается при пуше в master
    - if: $CI_COMMIT_BRANCH == "master"

types:
  stage: checks
  image: $NODE_IMAGE
  script:
    - yarn check:types
  needs:
    - install_dependencies
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  rules:
    # Запускается для merge request в develop/master
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master")
    # Запускается при пуше в master
    - if: $CI_COMMIT_BRANCH == "master"

build:
  stage: checks
  image: $NODE_IMAGE
  variables:
    NODE_ENV: production
  script:
    - yarn install --frozen-lockfile
    - yarn build
  cache: {}
  rules:
    # Запускается для merge request в develop/master
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master")
    # Запускается при пуше в master
    - if: $CI_COMMIT_BRANCH == "master"

deploy:
  stage: deploy
  script:
    - docker compose -f docker-compose.yml up -d --build
  needs:
    - linter
    - prettier
    - types
    - build
  tags:
    - gallery
    - backend
    - production
  rules:
    # Запускается при пуше в master
    - if: '$CI_COMMIT_BRANCH == "master"'
