services:
  backend:
    build:
      context: .
    container_name: backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
    restart: always
    ports:
      - 7777:3000
    command: node dist/main.js
